### ISSUE TITLE
Add a additional tab and a new page for blogs

### ISSUE THREAD

**Issue by hari-sikchi** [hari-sikchi/hari-sikchi.github.io#1]
Need a new tab next to other tabs named blog that links to a new page in the same template as present web-page.

**Comment by rafajaques** [comment]
You need a new anchor?

**Comment by hari-sikchi** [comment]
Yes.The blog page should reflect the same texture as the main webpage

**Comment by realslimshanky** [comment]
I'm on it..!!

**Comment by ykshinde** [comment]
I created new pull request with the requested changes...

**Comment by realslimshanky** [comment]
I've added a PR with the issue resolved.

**Comment by hari-sikchi** [comment]
@realslimshanky Can you please add a blog.html which has a blogging format and links to the tab have added.
